### ISSUE TITLE
Getting "bash error" while compiling contract code

### ISSUE THREAD

**Issue by pawandhanwani** [Tezsure/Bundle-react#7]
`
'bash' is not recognized as an internal or external command,

operable program or batch file.

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! bundle-react@1.0.0 run-code: `bash ./utils/scripts/compileCode.sh`

npm ERR! Exit status 1
`

**Comment by dibyo007dev** [comment]
@pawandhanwani, we are not currently supporting Windows. As the operating scripts of smartpy-cli that are not supported in Windows.
